language: go
go:
- 1.x
os:
- linux
env:
- GO111MODULE=on
before_install:
# gox simplifies building for multiple architectures
- go get github.com/mitchellh/gox
script:
- go build ./...
- go test ./...
- go vet ./...
- mkdir linux
- mkdir darwin
- gox -os="linux darwin" -arch="amd64" -output="{{.OS}}/{{.Dir}}" ./cmd/noms
- gox -os="linux darwin" -arch="amd64" -output="{{.OS}}/{{.Dir}}" ./samples/go/csv/csv-import
- gox -os="linux darwin" -arch="amd64" -output="{{.OS}}/{{.Dir}}" ./samples/go/csv/csv-export
- gox -os="linux darwin" -arch="amd64" -output="{{.OS}}/{{.Dir}}" ./samples/go/xml-import
- mv darwin osx
- zip -r linux linux
- zip -r osx osx
deploy:
  overwrite: true
  provider: releases
  skip_cleanup: true
  file:
  - linux.zip
  - osx.zip
  on:
    repo: attic-labs/noms
    tags: true
